services:
  postgres:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks: [stack]

  mongodb:
    image: mongo:7
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-app}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-app}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username \"$${MONGO_INITDB_ROOT_USERNAME}\" --password \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase admin --eval \"db.adminCommand({ ping: 1 })\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks: [stack]

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_redis
    command: ["sh", "-c", "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-app}"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD:-app} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks: [stack]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-app}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-app}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
    
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks: [stack]

  app1:
    build:
      context: .
      dockerfile: docker/app1.Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_app1
    ports:
      - "${APP1_PORT:-8000}:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - MONGO_HOST=mongodb
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-app}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-app}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-app}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER:-app}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS:-app}
    volumes:
      - ./apps/app1:/app
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks: [stack]

  app2:
    build:
      context: .
      dockerfile: docker/app2.Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_app2
    ports:
      - "${APP2_PORT:-8001}:8001"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - MONGO_HOST=mongodb
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-app}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-app}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-app}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER:-app}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS:-app}
    volumes:
      - ./apps/app2:/app
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks: [stack]

  beginner-app:
    build:
      context: .
      dockerfile: projects/01-beginner/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_beginner
    ports:
      - "${BEGINNER_APP_PORT:-8002}:8002"
    environment:
      - BEGINNER_PROJECT_NAME=${BEGINNER_PROJECT_NAME:-Beginner FastAPI}
      - BEGINNER_ENVIRONMENT=${BEGINNER_ENVIRONMENT:-development}
      - BEGINNER_VERSION=${BEGINNER_VERSION:-0.1.0}
      - BEGINNER_API_PREFIX=${BEGINNER_API_PREFIX:-/api}
      - BEGINNER_APP_HOST=0.0.0.0
      - BEGINNER_APP_PORT=${BEGINNER_APP_PORT:-8002}
      - BEGINNER_RELOAD=${BEGINNER_RELOAD:-true}
      - BEGINNER_LOG_LEVEL=${BEGINNER_LOG_LEVEL:-INFO}
      - BEGINNER_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-app_db}
      - BEGINNER_DB_ECHO=${BEGINNER_DB_ECHO:-false}
      - BEGINNER_ALLOWED_ORIGINS=${BEGINNER_ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - BEGINNER_ALLOW_CREDENTIALS=${BEGINNER_ALLOW_CREDENTIALS:-true}
      - BEGINNER_ALLOW_METHODS=${BEGINNER_ALLOW_METHODS:-*}
      - BEGINNER_ALLOW_HEADERS=${BEGINNER_ALLOW_HEADERS:-*}
      - BEGINNER_JWT_SECRET_KEY=${BEGINNER_JWT_SECRET_KEY:-change-me}
      - BEGINNER_JWT_ALGORITHM=${BEGINNER_JWT_ALGORITHM:-HS256}
      - BEGINNER_ACCESS_TOKEN_EXPIRE_MINUTES=${BEGINNER_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    volumes:
      - ./src:/srv/app/src
      - ./projects/01-beginner:/srv/app/projects/01-beginner
    depends_on:
      postgres:
        condition: service_healthy
    networks: [stack]

  intermediate-app:
    build:
      context: .
      dockerfile: projects/02-intermediate/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_intermediate
    ports:
      - "${INTERMEDIATE_APP_PORT:-8003}:8003"
    environment:
      - INTERMEDIATE_PROJECT_NAME=${INTERMEDIATE_PROJECT_NAME:-Intermediate FastAPI}
      - INTERMEDIATE_ENVIRONMENT=${INTERMEDIATE_ENVIRONMENT:-development}
      - INTERMEDIATE_VERSION=${INTERMEDIATE_VERSION:-0.1.0}
      - INTERMEDIATE_API_PREFIX=${INTERMEDIATE_API_PREFIX:-/api}
      - INTERMEDIATE_APP_HOST=0.0.0.0
      - INTERMEDIATE_APP_PORT=${INTERMEDIATE_APP_PORT:-8003}
      - INTERMEDIATE_RELOAD=${INTERMEDIATE_RELOAD:-true}
      - INTERMEDIATE_LOG_LEVEL=${INTERMEDIATE_LOG_LEVEL:-INFO}
      - INTERMEDIATE_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-app_db}
      - INTERMEDIATE_DB_ECHO=${INTERMEDIATE_DB_ECHO:-false}
      - INTERMEDIATE_REDIS_URL=redis://:${REDIS_PASSWORD:-app}@redis:${REDIS_PORT:-6379}/0
      - INTERMEDIATE_JOB_QUEUE_NAME=${INTERMEDIATE_JOB_QUEUE_NAME:-intermediate:tasks}
      - INTERMEDIATE_JOB_WORKER_NAME=${INTERMEDIATE_JOB_WORKER_NAME:-intermediate-worker}
      - INTERMEDIATE_JOB_TIMEOUT_SECONDS=${INTERMEDIATE_JOB_TIMEOUT_SECONDS:-300}
      - INTERMEDIATE_JOB_RESULT_TTL_SECONDS=${INTERMEDIATE_JOB_RESULT_TTL_SECONDS:-600}
      - INTERMEDIATE_JOB_MAX_RETRIES=${INTERMEDIATE_JOB_MAX_RETRIES:-3}
      - INTERMEDIATE_JOB_RETRY_BACKOFF_SECONDS=${INTERMEDIATE_JOB_RETRY_BACKOFF_SECONDS:-5,15,30}
      - INTERMEDIATE_JWT_SECRET_KEY=${INTERMEDIATE_JWT_SECRET_KEY:-change-me}
      - INTERMEDIATE_JWT_REFRESH_SECRET_KEY=${INTERMEDIATE_JWT_REFRESH_SECRET_KEY:-change-me-refresh}
      - INTERMEDIATE_JWT_ALGORITHM=${INTERMEDIATE_JWT_ALGORITHM:-HS256}
      - INTERMEDIATE_ACCESS_TOKEN_EXPIRE_MINUTES=${INTERMEDIATE_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - INTERMEDIATE_REFRESH_TOKEN_EXPIRE_MINUTES=${INTERMEDIATE_REFRESH_TOKEN_EXPIRE_MINUTES:-1440}
      - INTERMEDIATE_SESSION_SECRET_KEY=${INTERMEDIATE_SESSION_SECRET_KEY:-change-me-session}
      - INTERMEDIATE_SESSION_COOKIE_NAME=${INTERMEDIATE_SESSION_COOKIE_NAME:-intermediate_session}
      - INTERMEDIATE_SESSION_MAX_AGE=${INTERMEDIATE_SESSION_MAX_AGE:-1209600}
      - INTERMEDIATE_SESSION_HTTPS_ONLY=${INTERMEDIATE_SESSION_HTTPS_ONLY:-false}
      - INTERMEDIATE_SESSION_SAME_SITE=${INTERMEDIATE_SESSION_SAME_SITE:-lax}
      - INTERMEDIATE_ALLOWED_ORIGINS=${INTERMEDIATE_ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - INTERMEDIATE_ALLOW_CREDENTIALS=${INTERMEDIATE_ALLOW_CREDENTIALS:-true}
      - INTERMEDIATE_ALLOW_METHODS=${INTERMEDIATE_ALLOW_METHODS:-*}
      - INTERMEDIATE_ALLOW_HEADERS=${INTERMEDIATE_ALLOW_HEADERS:-*}
    volumes:
      - ./src:/srv/app/src
      - ./projects/02-intermediate:/srv/app/projects/02-intermediate
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [stack]

  intermediate-worker:
    build:
      context: .
      dockerfile: projects/02-intermediate/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_intermediate_worker
    command: ["poetry", "run", "intermediate-worker"]
    restart: unless-stopped
    environment:
      - INTERMEDIATE_PROJECT_NAME=${INTERMEDIATE_PROJECT_NAME:-Intermediate FastAPI}
      - INTERMEDIATE_ENVIRONMENT=${INTERMEDIATE_ENVIRONMENT:-development}
      - INTERMEDIATE_VERSION=${INTERMEDIATE_VERSION:-0.1.0}
      - INTERMEDIATE_API_PREFIX=${INTERMEDIATE_API_PREFIX:-/api}
      - INTERMEDIATE_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-app_db}
      - INTERMEDIATE_DB_ECHO=${INTERMEDIATE_DB_ECHO:-false}
      - INTERMEDIATE_REDIS_URL=redis://:${REDIS_PASSWORD:-app}@redis:${REDIS_PORT:-6379}/0
      - INTERMEDIATE_JOB_QUEUE_NAME=${INTERMEDIATE_JOB_QUEUE_NAME:-intermediate:tasks}
      - INTERMEDIATE_JOB_WORKER_NAME=${INTERMEDIATE_JOB_WORKER_NAME:-intermediate-worker}
      - INTERMEDIATE_JOB_TIMEOUT_SECONDS=${INTERMEDIATE_JOB_TIMEOUT_SECONDS:-300}
      - INTERMEDIATE_JOB_RESULT_TTL_SECONDS=${INTERMEDIATE_JOB_RESULT_TTL_SECONDS:-600}
      - INTERMEDIATE_JOB_MAX_RETRIES=${INTERMEDIATE_JOB_MAX_RETRIES:-3}
      - INTERMEDIATE_JOB_RETRY_BACKOFF_SECONDS=${INTERMEDIATE_JOB_RETRY_BACKOFF_SECONDS:-5,15,30}
    volumes:
      - ./src:/srv/app/src
      - ./projects/02-intermediate:/srv/app/projects/02-intermediate
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [stack]

  advanced-app:
    build:
      context: .
      dockerfile: projects/03-advanced/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_advanced_app
    ports:
      - "${ADVANCED_APP_PORT:-8004}:8004"
    environment:
      - ADVANCED_REALTIME_TOKEN=${ADVANCED_REALTIME_TOKEN:-change-me-realtime}
      - ADVANCED_ALLOWED_ORIGINS=${ADVANCED_ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - ADVANCED_ACTIVITY_CHANNEL=${ADVANCED_ACTIVITY_CHANNEL:-advanced:activity}
      - ADVANCED_REDIS_URL=redis://:${REDIS_PASSWORD:-app}@redis:${REDIS_PORT:-6379}/2
      - ADVANCED_REDIS_IDEMPOTENCY_PREFIX=${ADVANCED_REDIS_IDEMPOTENCY_PREFIX:-advanced:idempotency}
      - ADVANCED_REDIS_IDEMPOTENCY_TTL_SECONDS=${ADVANCED_REDIS_IDEMPOTENCY_TTL_SECONDS:-300}
      - ADVANCED_EVENT_TRANSPORT=rabbitmq
      - ADVANCED_RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER:-app}:${RABBITMQ_DEFAULT_PASS:-app}@rabbitmq:${RABBITMQ_PORT:-5672}/
      - ADVANCED_RABBITMQ_EXCHANGE=${ADVANCED_RABBITMQ_EXCHANGE:-advanced.board.events}
      - ADVANCED_RABBITMQ_QUEUE=${ADVANCED_RABBITMQ_QUEUE:-advanced.board.events}
      - ADVANCED_RABBITMQ_RETRY_EXCHANGE=${ADVANCED_RABBITMQ_RETRY_EXCHANGE:-advanced.board.events.retry}
      - ADVANCED_RABBITMQ_RETRY_QUEUE=${ADVANCED_RABBITMQ_RETRY_QUEUE:-advanced.board.events.retry}
      - ADVANCED_RABBITMQ_DLQ_EXCHANGE=${ADVANCED_RABBITMQ_DLQ_EXCHANGE:-advanced.board.events.dlq}
      - ADVANCED_RABBITMQ_DLQ_QUEUE=${ADVANCED_RABBITMQ_DLQ_QUEUE:-advanced.board.events.dlq}
      - ADVANCED_RABBITMQ_RETRY_DELAY_MS=${ADVANCED_RABBITMQ_RETRY_DELAY_MS:-5000}
      - ADVANCED_RABBITMQ_MAX_RETRIES=${ADVANCED_RABBITMQ_MAX_RETRIES:-5}
      - ADVANCED_RABBITMQ_PREFETCH_COUNT=${ADVANCED_RABBITMQ_PREFETCH_COUNT:-16}
    volumes:
      - ./src:/srv/app/src
      - ./projects/03-advanced:/srv/app/projects/03-advanced
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks: [stack]

  advanced-worker:
    build:
      context: .
      dockerfile: projects/03-advanced/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_advanced_worker
    command: ["poetry", "run", "advanced-worker"]
    restart: unless-stopped
    environment:
      - ADVANCED_REALTIME_TOKEN=${ADVANCED_REALTIME_TOKEN:-change-me-realtime}
      - ADVANCED_ACTIVITY_CHANNEL=${ADVANCED_ACTIVITY_CHANNEL:-advanced:activity}
      - ADVANCED_REDIS_URL=redis://:${REDIS_PASSWORD:-app}@redis:${REDIS_PORT:-6379}/2
      - ADVANCED_REDIS_IDEMPOTENCY_PREFIX=${ADVANCED_REDIS_IDEMPOTENCY_PREFIX:-advanced:idempotency}
      - ADVANCED_REDIS_IDEMPOTENCY_TTL_SECONDS=${ADVANCED_REDIS_IDEMPOTENCY_TTL_SECONDS:-300}
      - ADVANCED_EVENT_TRANSPORT=rabbitmq
      - ADVANCED_RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER:-app}:${RABBITMQ_DEFAULT_PASS:-app}@rabbitmq:${RABBITMQ_PORT:-5672}/
      - ADVANCED_RABBITMQ_EXCHANGE=${ADVANCED_RABBITMQ_EXCHANGE:-advanced.board.events}
      - ADVANCED_RABBITMQ_QUEUE=${ADVANCED_RABBITMQ_QUEUE:-advanced.board.events}
      - ADVANCED_RABBITMQ_RETRY_EXCHANGE=${ADVANCED_RABBITMQ_RETRY_EXCHANGE:-advanced.board.events.retry}
      - ADVANCED_RABBITMQ_RETRY_QUEUE=${ADVANCED_RABBITMQ_RETRY_QUEUE:-advanced.board.events.retry}
      - ADVANCED_RABBITMQ_DLQ_EXCHANGE=${ADVANCED_RABBITMQ_DLQ_EXCHANGE:-advanced.board.events.dlq}
      - ADVANCED_RABBITMQ_DLQ_QUEUE=${ADVANCED_RABBITMQ_DLQ_QUEUE:-advanced.board.events.dlq}
      - ADVANCED_RABBITMQ_RETRY_DELAY_MS=${ADVANCED_RABBITMQ_RETRY_DELAY_MS:-5000}
      - ADVANCED_RABBITMQ_MAX_RETRIES=${ADVANCED_RABBITMQ_MAX_RETRIES:-5}
      - ADVANCED_RABBITMQ_PREFETCH_COUNT=${ADVANCED_RABBITMQ_PREFETCH_COUNT:-16}
    volumes:
      - ./src:/srv/app/src
      - ./projects/03-advanced:/srv/app/projects/03-advanced
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks: [stack]

  rq-dashboard:
    image: eoranged/rq-dashboard:latest
    container_name: ${COMPOSE_PROJECT_NAME:-devstack}_rq_dashboard
    ports:
      - "${RQ_DASHBOARD_PORT:-9181}:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://:${REDIS_PASSWORD:-app}@redis:${REDIS_PORT:-6379}/0
    depends_on:
      redis:
        condition: service_healthy
    networks: [stack]

networks:
  stack:
    name: ${COMPOSE_PROJECT_NAME:-devstack}_net

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:
